# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s_count = Counter(s)
        for i, j in Counter(t).items():
            if j != s_count[i]:
                return i
